import s from '@/styles/index.module.scss';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>

        <div className={s.banner}>
          <Image
            className={s.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={s.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={s.grid}>
          <a
            href="/"
            className={s.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Save <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Easily upload and save your&nbsp;memes from anywhere.
            </p>
          </a>

          <a
            href="/"
            className={s.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Store <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Securely store your memes in the&nbsp;cloud for easy access.
            </p>
          </a>

          <a
            href="/"
            className={s.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Search <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly find that meme you just can&#39;t remember the name of.
            </p>
          </a>

          <a
            href="/"
            className={s.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Share <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Share your memes with friends and family with just a tap.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
